apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vc.yaml
  - sd.yaml
  - anthony-ganley.yaml
  - dale-wright.yaml
  - jonathan-dunn.yaml
  - kelly-heys.yaml
  - kristian-heaton.yaml
  - matthew-cartwright1.yaml
  - michael-adekoya.yaml
  - mubean-patel.yaml
  - percy-moyo.yaml
  - sai-s.yaml
  - timothy-howcroft.yaml
  - zuber-ismail.yaml

patchesStrategicMerge:
  - image-update-patch.yaml
