apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vc.yaml
  - sd.yaml
  - alex-hocquigny.yaml
  - anthony-ganley.yaml
  - dale-wright.yaml
  - jonathan-dunn.yaml
  - kelly-heys.yaml
  - kristian-heaton.yaml
  - mark-fowkes.yaml
  - matthew-cartwright1.yaml
  - michael-adekoya.yaml
  - mubean-patel.yaml
  - percy-moyo.yaml
  - sai-s.yaml
  - stephen-elves.yaml
  - steve-bates.yaml
  - timothy-howcroft.yaml
  - zuber-ismail.yaml

patches:
  - path: _workspace-patch.yaml
    target:
      kind: AnalyticsWorkspace
      labelSelector: "app=sqlmesh"
